name: CI/CD Pipeline - Auto Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: cd package.json       

      - name: Build Docker image
        run: docker build -t ${{ github.repository }} .

      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app
            docker tag ${{ github.repository }} $IMAGE
            docker push $IMAGE
